name: Ticketing System

services:
  booking-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: booking-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1990
    ports:
      - "1433:1433"

    volumes:
      - booking-db-data:/var/opt/mssql

  booking-api:
    build:
      context: ./src
      dockerfile: BookingService/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=booking-db;Database=BookingDb;User Id=sa;Password=Password@1990;Encrypt=True;TrustServerCertificate=True;
    expose:
      - "8080"
    depends_on:
      - booking-db

  k6:
    image: loadimpact/k6:latest
    container_name: k6-tester
    volumes:
      - ./k6:/scripts
    environment:
      - API_URL=http://booking-api:8080
    depends_on:
      - booking-api

volumes:
  booking-db-data:
